### ISSUE TITLE
Buat File Baru Lat Issue

### ISSUE THREAD

**Issue by masMAY** [masMAY/Latihan-Dasar-Python#2]
Membuat Latihan File Baru di directory baru dg nama Lat Issue

**Comment by mujib-programmer** [comment]
Apakah yang dimaksud membuat file lat_issue.txt?

**Comment by masMAY** [comment]
Betul Membuat file lat_issue.txt di directory Lat Issue

**Comment by mujib-programmer** [comment]
Baik saya akan membuatnya di /Lat_issue/lat_issue.txt.
@masMAY Tolong beritahu jika tidak seperti itu yang diharapkan.

**Comment by masMAY** [comment]
close by Pull Request on https://github.com/masMAY/Latihan-Dasar-Python/pull/3
